export const drugServices = [
  // ── Analgesics & Anti-inflammatories ──────────────────────────────────────
  { name: "Paracetamol 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Paracetamol 1g Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Paracetamol Syrup 120mg/5ml", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Paracetamol Suppository 125mg", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Paracetamol Suppository 250mg", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Paracetamol Injection 1g/100ml", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ibuprofen 200mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ibuprofen 400mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ibuprofen 600mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ibuprofen Syrup 100mg/5ml", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Diclofenac 25mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Diclofenac 50mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Diclofenac 75mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Diclofenac Injection 75mg/3ml", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Diclofenac Gel 1%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Diclofenac Suppository 100mg", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Naproxen 250mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Naproxen 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Indomethacin 25mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Indomethacin 50mg Suppository", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Piroxicam 20mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Celecoxib 100mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Celecoxib 200mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Meloxicam 7.5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Meloxicam 15mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tramadol 50mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tramadol 100mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tramadol/Paracetamol 37.5/325mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Morphine Sulphate 10mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Pethidine 100mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Pentazocine 30mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Aspirin 75mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Aspirin 300mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ketorolac 30mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Codeine 30mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Codeine Cough Syrup", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Antibiotics ───────────────────────────────────────────────────────────
  { name: "Amoxicillin 250mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Amoxicillin 500mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Amoxicillin 125mg/5ml Syrup", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Amoxicillin 250mg/5ml Syrup", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Amoxicillin/Clavulanate 375mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Amoxicillin/Clavulanate 625mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Amoxicillin/Clavulanate Suspension 228mg/5ml", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ampicillin 250mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ampicillin 500mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ampicillin/Cloxacillin 250mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cloxacillin 250mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cloxacillin 500mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cloxacillin 500mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Penicillin V 250mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Benzylpenicillin 1M IU Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Benzathine Penicillin 1.2M IU Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Benzathine Penicillin 2.4M IU Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Procaine Penicillin 4M IU Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ciprofloxacin 250mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ciprofloxacin 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ciprofloxacin 200mg/100ml Infusion", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ciprofloxacin Eye Drops 0.3%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Levofloxacin 250mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Levofloxacin 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Levofloxacin 750mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Levofloxacin 500mg/100ml Infusion", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ofloxacin 200mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ofloxacin 400mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Metronidazole 200mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Metronidazole 400mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Metronidazole 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Metronidazole 200mg/5ml Suspension", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Metronidazole 500mg/100ml Infusion", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Metronidazole Gel 0.75%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tinidazole 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Azithromycin 250mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Azithromycin 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Azithromycin 200mg/5ml Suspension", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Erythromycin 250mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Erythromycin 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Erythromycin 125mg/5ml Suspension", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Clarithromycin 250mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Clarithromycin 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Doxycycline 100mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tetracycline 250mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tetracycline Eye Ointment 1%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ceftriaxone 250mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ceftriaxone 500mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ceftriaxone 1g Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ceftriaxone 2g Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cefuroxime 250mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cefuroxime 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cefuroxime 750mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cefuroxime 1.5g Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cefixime 200mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cefixime 400mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cefixime 100mg/5ml Suspension", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cefpodoxime 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cefpodoxime 200mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ceftazidime 1g Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ceftazidime 2g Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cefotaxime 1g Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cefotaxime 2g Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Meropenem 500mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Meropenem 1g Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Imipenem/Cilastatin 500mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ertapenem 1g Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Gentamicin 40mg/2ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Gentamicin 80mg/2ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Amikacin 250mg/2ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Amikacin 500mg/2ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Chloramphenicol 250mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Chloramphenicol 1g Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Chloramphenicol Eye Drops 0.5%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Chloramphenicol Eye Ointment 1%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Nitrofurantoin 50mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Nitrofurantoin 100mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Trimethoprim 200mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cotrimoxazole 480mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cotrimoxazole 960mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cotrimoxazole 240mg/5ml Suspension", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vancomycin 500mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vancomycin 1g Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Clindamycin 150mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Clindamycin 300mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Clindamycin 300mg/2ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Clindamycin 600mg/4ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Linezolid 600mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Linezolid 600mg/300ml Infusion", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Piperacillin/Tazobactam 2.25g Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Piperacillin/Tazobactam 4.5g Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Antimalarials ─────────────────────────────────────────────────────────
  { name: "Artemether/Lumefantrine 20/120mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Artemether/Lumefantrine 40/240mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Coartem Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Artesunate 60mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Artesunate 120mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Artesunate/Amodiaquine Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Dihydroartemisinin/Piperaquine Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Artemether 80mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Quinine Sulphate 300mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Quinine Dihydrochloride 300mg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Chloroquine 150mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Chloroquine Syrup 50mg/5ml", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Proguanil 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Atovaquone/Proguanil 250/100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Mefloquine 250mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Primaquine 7.5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Primaquine 15mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Sulfadoxine/Pyrimethamine Tablet (SP)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Rectal Artesunate 100mg Suppository", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Antifungals ───────────────────────────────────────────────────────────
  { name: "Fluconazole 50mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Fluconazole 150mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Fluconazole 200mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Fluconazole 200mg/100ml Infusion", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Itraconazole 100mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Itraconazole 200mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Voriconazole 200mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Amphotericin B 50mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Liposomal Amphotericin B 50mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Nystatin 100,000 IU/ml Suspension", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Nystatin Cream 100,000 IU/g", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Nystatin Pessary 100,000 IU", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Griseofulvin 125mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Griseofulvin 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Terbinafine 250mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Terbinafine Cream 1%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ketoconazole 200mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ketoconazole Cream 2%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ketoconazole Shampoo 2%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Clotrimazole Cream 1%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Clotrimazole Pessary 100mg", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Clotrimazole Pessary 500mg", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Miconazole Cream 2%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Miconazole Oral Gel 20mg/g", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Antivirals ────────────────────────────────────────────────────────────
  { name: "Acyclovir 200mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Acyclovir 400mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Acyclovir 800mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Acyclovir 250mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Acyclovir Cream 5%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Valacyclovir 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Valacyclovir 1000mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Oseltamivir 75mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Oseltamivir 12mg/ml Suspension", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ribavirin 200mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lamivudine 150mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lamivudine 300mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tenofovir/Lamivudine/Efavirenz Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tenofovir/Lamivudine/Dolutegravir Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tenofovir Disoproxil 300mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Efavirenz 200mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Efavirenz 600mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lopinavir/Ritonavir 200/50mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Nevirapine 200mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Nevirapine Suspension 10mg/ml", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Antiparasitics & Anthelmintics ────────────────────────────────────────
  { name: "Albendazole 200mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Albendazole 400mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Mebendazole 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Mebendazole 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Praziquantel 600mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ivermectin 3mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ivermectin 6mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Diethylcarbamazine 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Levamisole 50mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Pyrantel 250mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Pyrantel 50mg/ml Suspension", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Metronidazole 200mg Tablet (Antiprotozoal)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Diloxanide Furoate 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Suramin Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Permethrin Cream 5%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Benzyl Benzoate Lotion 25%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Antituberculosis ──────────────────────────────────────────────────────
  { name: "Rifampicin 150mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Rifampicin 300mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Rifampicin 450mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Isoniazid 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Isoniazid 300mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ethambutol 400mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ethambutol 800mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Pyrazinamide 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Streptomycin 1g Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Rifampicin/Isoniazid/Pyrazinamide/Ethambutol Tablet (RHZE)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Rifampicin/Isoniazid Tablet (RH)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Cardiovascular ────────────────────────────────────────────────────────
  { name: "Amlodipine 2.5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Amlodipine 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Amlodipine 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Nifedipine 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Nifedipine 20mg SR Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Nifedipine 30mg SR Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Diltiazem 60mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Diltiazem 120mg SR Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Verapamil 40mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Verapamil 80mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Verapamil 5mg/2ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lisinopril 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lisinopril 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lisinopril 20mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Enalapril 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Enalapril 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Enalapril 20mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ramipril 2.5mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ramipril 5mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ramipril 10mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Perindopril 4mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Perindopril 8mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Losartan 25mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Losartan 50mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Losartan 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Valsartan 80mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Valsartan 160mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Telmisartan 40mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Telmisartan 80mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Irbesartan 150mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Irbesartan 300mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Hydrochlorothiazide 12.5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Hydrochlorothiazide 25mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Furosemide 20mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Furosemide 40mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Furosemide 10mg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Spironolactone 25mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Spironolactone 50mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Spironolactone 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Indapamide 1.5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Indapamide 2.5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Atenolol 25mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Atenolol 50mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Atenolol 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Metoprolol 25mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Metoprolol 50mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Metoprolol 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Propranolol 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Propranolol 40mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Carvedilol 3.125mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Carvedilol 6.25mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Carvedilol 12.5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Carvedilol 25mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Bisoprolol 2.5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Bisoprolol 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Bisoprolol 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Labetalol 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Labetalol 200mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Labetalol 5mg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Hydralazine 25mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Hydralazine 50mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Hydralazine 20mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Methyldopa 250mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Methyldopa 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Prazosin 1mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Prazosin 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Digoxin 0.0625mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Digoxin 0.125mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Digoxin 0.25mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Digoxin 0.25mg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Amiodarone 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Amiodarone 200mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Amiodarone 150mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Nitroglycerine (GTN) 0.5mg Sublingual Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Nitroglycerine Spray 400mcg/dose", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Isosorbide Dinitrate 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Isosorbide Mononitrate 20mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Isosorbide Mononitrate 60mg SR Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Adrenaline (Epinephrine) 1mg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Noradrenaline 4mg/4ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Dopamine 200mg/5ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Dobutamine 250mg/5ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Adenosine 6mg/2ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Atropine 0.6mg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Sodium Nitroprusside 50mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Potassium Chloride 15% Injection Concentrate", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Magnesium Sulphate 50% Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Lipid-lowering agents ─────────────────────────────────────────────────
  { name: "Atorvastatin 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Atorvastatin 20mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Atorvastatin 40mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Atorvastatin 80mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Simvastatin 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Simvastatin 20mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Simvastatin 40mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Rosuvastatin 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Rosuvastatin 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Rosuvastatin 20mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Fenofibrate 145mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Gemfibrozil 600mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Anticoagulants & Antiplatelets ────────────────────────────────────────
  { name: "Heparin 1000 IU/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Heparin 5000 IU/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Enoxaparin 40mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Enoxaparin 60mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Enoxaparin 80mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Enoxaparin 100mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Warfarin 1mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Warfarin 2mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Warfarin 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Clopidogrel 75mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ticagrelor 90mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Streptokinase 1.5M IU Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Alteplase 50mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Protamine Sulphate 50mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tranexamic Acid 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tranexamic Acid 1g/10ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vitamin K (Phytomenadione) 10mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Endocrine / Diabetes ──────────────────────────────────────────────────
  { name: "Metformin 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Metformin 850mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Metformin 1000mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Glibenclamide 2.5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Glibenclamide 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Glipizide 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Glipizide 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Gliclazide 80mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Gliclazide 30mg MR Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Sitagliptin 50mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Sitagliptin 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Empagliflozin 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Empagliflozin 25mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Dapagliflozin 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Insulin Regular 100IU/ml Injection (10ml)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Insulin NPH 100IU/ml Injection (10ml)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Insulin Glargine 100IU/ml Injection (10ml)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Insulin Lispro 100IU/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Insulin Aspart 100IU/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Insulin Detemir 100IU/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Insulin 30/70 Mixture 100IU/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Glucagon 1mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Dextrose 50% Injection 50ml", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Levothyroxine 25mcg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Levothyroxine 50mcg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Levothyroxine 100mcg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Carbimazole 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Carbimazole 20mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Propylthiouracil 50mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Corticosteroids ───────────────────────────────────────────────────────
  { name: "Prednisolone 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Prednisolone 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Prednisolone 25mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Prednisolone 1mg/ml Syrup", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Dexamethasone 0.5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Dexamethasone 4mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Dexamethasone 4mg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Hydrocortisone 100mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Hydrocortisone 200mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Hydrocortisone Cream 1%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Methylprednisolone 4mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Methylprednisolone 16mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Methylprednisolone 500mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Betamethasone 0.5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Betamethasone Cream 0.05%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Betamethasone Valerate Cream 0.1%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Triamcinolone 40mg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Budesonide 200mcg Inhaler", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Fluticasone 50mcg Inhaler", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Fluticasone 125mcg Inhaler", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Beclomethasone 50mcg Inhaler", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Beclomethasone 100mcg Inhaler", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Respiratory ───────────────────────────────────────────────────────────
  { name: "Salbutamol 2mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Salbutamol 4mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Salbutamol 100mcg Inhaler (MDI)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Salbutamol 2mg/5ml Syrup", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Salbutamol 5mg/ml Nebulizer Solution", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ipratropium 20mcg Inhaler", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ipratropium 250mcg/ml Nebulizer Solution", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Salbutamol/Ipratropium Nebulizer Solution", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tiotropium 18mcg Inhaler Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Salmeterol 25mcg Inhaler", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Formoterol 12mcg Inhaler Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Fluticasone/Salmeterol 125/25mcg Inhaler", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Budesonide/Formoterol 160/4.5mcg Inhaler", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Theophylline 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Theophylline 200mg SR Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Aminophylline 250mg/10ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Montelukast 4mg Chewable Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Montelukast 5mg Chewable Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Montelukast 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ambroxol 30mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ambroxol 15mg/5ml Syrup", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Bromhexine 8mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Carbocisteine 375mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "N-Acetylcysteine 600mg Effervescent Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Dextromethorphan 15mg/5ml Syrup", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Gastrointestinal ──────────────────────────────────────────────────────
  { name: "Omeprazole 10mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Omeprazole 20mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Omeprazole 40mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Omeprazole 40mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Pantoprazole 20mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Pantoprazole 40mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Pantoprazole 40mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Esomeprazole 20mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Esomeprazole 40mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lansoprazole 15mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lansoprazole 30mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ranitidine 150mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ranitidine 300mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ranitidine 50mg/2ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Famotidine 20mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Famotidine 40mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Antacid (Aluminium/Magnesium) Suspension", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Antacid (Aluminium/Magnesium) Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Sucralfate 1g Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Misoprostol 200mcg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Metoclopramide 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Metoclopramide 10mg/2ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Domperidone 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Domperidone 5mg/5ml Suspension", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ondansetron 4mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ondansetron 8mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ondansetron 4mg/2ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ondansetron 8mg Wafer/ODT", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Granisetron 1mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Granisetron 1mg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Prochlorperazine 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Prochlorperazine 12.5mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Bisacodyl 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Bisacodyl 10mg Suppository", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lactulose 3.35g/5ml Syrup", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Macrogol (PEG 3350) Sachet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Senna 7.5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Glycerol Suppository Adult", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Glycerol Suppository Child", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Loperamide 2mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "ORS Sachet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cholestyramine 4g Sachet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Mesalazine 400mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Mesalazine 800mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Mesalazine 500mg Suppository", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Hyoscine Butylbromide 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Hyoscine Butylbromide 20mg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Simethicone 80mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Activated Charcoal 50g Powder", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Neostigmine 2.5mg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lactulose Solution 300ml", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Neurology & CNS ───────────────────────────────────────────────────────
  { name: "Phenobarbital 30mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Phenobarbital 60mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Phenobarbital 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Phenobarbital 200mg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Phenytoin 100mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Phenytoin 50mg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Carbamazepine 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Carbamazepine 200mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Carbamazepine 400mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Carbamazepine 100mg/5ml Suspension", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Sodium Valproate 200mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Sodium Valproate 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Sodium Valproate 200mg/5ml Syrup", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Sodium Valproate 400mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lamotrigine 25mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lamotrigine 50mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lamotrigine 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Levetiracetam 250mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Levetiracetam 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Levetiracetam 1000mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Levetiracetam 500mg/5ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Diazepam 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Diazepam 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Diazepam 5mg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Diazepam 5mg Rectal Tube", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lorazepam 1mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lorazepam 2mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lorazepam 4mg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Midazolam 5mg/5ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Midazolam 15mg/3ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Clonazepam 0.5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Clonazepam 2mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Haloperidol 1.5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Haloperidol 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Haloperidol 5mg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Chlorpromazine 25mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Chlorpromazine 50mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Chlorpromazine 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Chlorpromazine 25mg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Risperidone 1mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Risperidone 2mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Olanzapine 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Olanzapine 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Olanzapine 10mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Amitriptyline 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Amitriptyline 25mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Sertraline 25mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Sertraline 50mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Sertraline 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Fluoxetine 20mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Fluoxetine 40mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Escitalopram 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Escitalopram 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Escitalopram 20mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Paroxetine 20mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lithium Carbonate 250mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lithium Carbonate 400mg SR Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Biperiden 2mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Biperiden 5mg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Levodopa/Carbidopa 100/25mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Levodopa/Carbidopa 250/25mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Sumatriptan 50mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Sumatriptan 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ergotamine 1mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Promethazine 25mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Promethazine 25mg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Antihistamines ────────────────────────────────────────────────────────
  { name: "Loratadine 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Loratadine 5mg/5ml Syrup", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cetirizine 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cetirizine 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cetirizine 5mg/5ml Syrup", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Fexofenadine 120mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Fexofenadine 180mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Chlorpheniramine 4mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Chlorpheniramine 2mg/5ml Syrup", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Diphenhydramine 25mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Diphenhydramine Syrup 12.5mg/5ml", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Hydroxyzine 25mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Hydroxyzine 10mg/5ml Syrup", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Vitamins, Minerals & Nutritional Supplements ──────────────────────────
  { name: "Vitamin A 200,000 IU Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vitamin A 100,000 IU Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vitamin B1 (Thiamine) 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vitamin B1 100mg/2ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vitamin B2 (Riboflavin) 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vitamin B6 (Pyridoxine) 25mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vitamin B6 50mg/2ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vitamin B12 (Cyanocobalamin) 1000mcg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vitamin B12 1000mcg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vitamin B Complex Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vitamin B Complex Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vitamin C 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vitamin C 250mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vitamin C 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vitamin C 1000mg Effervescent Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vitamin D3 800 IU Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vitamin D3 1000 IU Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vitamin D3 50,000 IU Capsule (Weekly)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vitamin D3 600,000 IU/2ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vitamin E 100mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vitamin E 400 IU Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Folic Acid 0.4mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Folic Acid 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ferrous Sulphate 200mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ferrous Gluconate 300mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ferrous Sulphate 150mg/5ml Syrup", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Iron Polymaltose Complex Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Iron Sucrose 200mg/10ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Iron/Folic Acid Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Calcium Carbonate 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Calcium Carbonate 1000mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Calcium Gluconate 10% Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Calcium/Vitamin D3 Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Zinc Sulphate 20mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Zinc Sulphate 10mg/5ml Syrup", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Magnesium Hydroxide 400mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Magnesium Oxide 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Potassium Chloride 600mg SR Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Multivitamin + Mineral Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Multivitamin + Mineral Syrup", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Prenatal Multivitamin Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Paediatric Multivitamin Drops", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── IV Fluids & Electrolytes ──────────────────────────────────────────────
  { name: "Normal Saline 0.9% 500ml Infusion", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Normal Saline 0.9% 1000ml Infusion", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Normal Saline 0.9% 100ml Infusion", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Dextrose 5% in Water 500ml Infusion", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Dextrose 5% in Water 1000ml Infusion", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Dextrose 10% 500ml Infusion", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Dextrose 5% in Normal Saline 500ml Infusion", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Dextrose 5% in 0.45% Saline 500ml Infusion", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ringer's Lactate 500ml Infusion", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ringer's Lactate 1000ml Infusion", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Haemaccel (Gelatin) 500ml Infusion", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Hydroxyethyl Starch 6% 500ml Infusion", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Albumin 20% Solution 50ml", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Albumin 5% Solution 250ml", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Sodium Bicarbonate 8.4% 100ml Infusion", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Mannitol 20% 250ml Infusion", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Water for Injection 5ml Ampoule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Water for Injection 10ml Ampoule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "ORS Sachet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Obstetrics & Gynaecology ──────────────────────────────────────────────
  { name: "Oxytocin 10 IU/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Oxytocin 5 IU in 500ml Saline Infusion", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ergometrine 0.5mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ergometrine/Oxytocin Tablet (Syntometrine)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Carboprost 250mcg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Misoprostol 200mcg Tablet (Obstetric)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Nifedipine 10mg Capsule (Tocolytic)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Atosiban 6.75mg/0.9ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Progesterone 200mg Pessary/Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Progesterone 100mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Progesterone 25mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Norethisterone 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Levonorgestrel 1.5mg Emergency Contraceptive Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Combined Oral Contraceptive Tablet (COC)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Depo-Provera (Medroxyprogesterone 150mg) Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Clomiphene 50mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Dydrogesterone 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Mifepristone 200mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tranexamic Acid 500mg Tablet (Menorrhagia)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Clotrimazole Vaginal Cream 1%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Metronidazole Vaginal Gel 0.75%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Estradiol Valerate 2mg Tablet (HRT)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Bromocriptine 2.5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cabergoline 0.5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Anaesthesia & ICU ─────────────────────────────────────────────────────
  { name: "Ketamine 500mg/10ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ketamine 200mg/10ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Propofol 200mg/20ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Propofol 500mg/50ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Thiopental Sodium 500mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Suxamethonium (Succinylcholine) 100mg/5ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Rocuronium 50mg/5ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vecuronium 4mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Pancuronium 4mg/2ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Sugammadex 200mg/2ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Neostigmine 2.5mg/5ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lignocaine (Lidocaine) 1% Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lignocaine 2% Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lignocaine with Adrenaline 2% Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Bupivacaine 0.5% Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Bupivacaine Heavy (Spinal) 0.5% Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Halothane Inhalation Agent 250ml", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Isoflurane Inhalation Agent 250ml", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Fentanyl 100mcg/2ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Fentanyl 500mcg/10ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Naloxone 0.4mg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Flumazenil 0.5mg/5ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Noradrenaline 8mg/8ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Vasopressin 20 IU/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Phenylephrine 100mcg/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Renal & Urology ───────────────────────────────────────────────────────
  { name: "Tamsulosin 0.4mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Doxazosin 2mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Doxazosin 4mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Finasteride 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Allopurinol 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Allopurinol 300mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Colchicine 0.5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Colchicine 1mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Acetazolamide 250mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Sodium Bicarbonate 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Oxybutynin 5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tolterodine 2mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Dermatology (topical) ─────────────────────────────────────────────────
  { name: "Calamine Lotion", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Zinc Oxide Ointment", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Zinc Oxide Paste", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Salicylic Acid 2% Ointment", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Salicylic Acid 6% Ointment", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Sulphur 10% Cream", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Coal Tar Shampoo 2%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Povidone Iodine 10% Solution", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Povidone Iodine Cream 10%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Povidone Iodine Ointment", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Silver Sulphadiazine Cream 1%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Mupirocin Ointment 2%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Fusidic Acid Cream 2%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Gentian Violet Solution 0.5%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Whitfield's Ointment", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Emulsifying Ointment (Aqueous Cream)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Liquid Paraffin / Petroleum Jelly", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lindane Lotion 1%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Selenium Sulphide Shampoo 2.5%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Acyclovir Cream 5%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tretinoin Cream 0.025%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Benzoyl Peroxide Cream 2.5%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Benzoyl Peroxide Cream 5%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Ophthalmology ─────────────────────────────────────────────────────────
  { name: "Chloramphenicol Eye Drops 0.5%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Chloramphenicol Eye Ointment 1%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ciprofloxacin Eye Drops 0.3%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Gentamicin Eye Drops 0.3%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tobramycin Eye Drops 0.3%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tetracycline Eye Ointment 1%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ofloxacin Eye Drops 0.3%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Dexamethasone Eye Drops 0.1%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Dexamethasone/Neomycin Eye Drops", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Prednisolone Eye Drops 1%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Atropine Eye Drops 1%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tropicamide Eye Drops 1%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Timolol Eye Drops 0.25%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Timolol Eye Drops 0.5%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Latanoprost Eye Drops 0.005%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Pilocarpine Eye Drops 2%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Artificial Tears Eye Drops", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Carbomer Gel Eye Drops", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Sodium Cromoglicate Eye Drops 2%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Fluorescein Sodium Eye Drops 1%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── ENT ───────────────────────────────────────────────────────────────────
  { name: "Xylometazoline Nasal Drops 0.05%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Xylometazoline Nasal Drops 0.1%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Oxymetazoline Nasal Spray 0.05%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Fluticasone Nasal Spray 50mcg", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Beclomethasone Nasal Spray 50mcg", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Sodium Chloride Nasal Saline Spray", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Hydrogen Peroxide Ear Drops 3%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Sofradex (Framycetin/Dexamethasone) Ear Drops", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ciprofloxacin Ear Drops 0.3%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Clotrimazole Ear Drops 1%", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Benzocaine/Glycerol Ear Drops", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Oncology (supportive) ─────────────────────────────────────────────────
  { name: "Ondansetron 8mg Tablet (Chemotherapy)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Granisetron 1mg Tablet (Chemotherapy)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Dexamethasone 8mg Injection (Antiemetic)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Metoclopramide 10mg Injection (Antiemetic)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Filgrastim 300mcg Injection (G-CSF)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Erythropoietin 4000 IU Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Leucovorin 15mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Mesna 400mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tamoxifen 10mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tamoxifen 20mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cyclophosphamide 50mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cyclophosphamide 500mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Methotrexate 2.5mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Methotrexate 50mg/2ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Imatinib 100mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Imatinib 400mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Blood Products & Haematinics ──────────────────────────────────────────
  { name: "Hydroxyurea 500mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Desferrioxamine 500mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Erythropoietin 10,000 IU Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Factor VIII Concentrate Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Fresh Frozen Plasma (FFP)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Whole Blood Transfusion Unit", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Packed Red Blood Cells (PRBC) Unit", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Platelet Concentrate Unit", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Immunosuppressants & Biologics ────────────────────────────────────────
  { name: "Azathioprine 50mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Mycophenolate Mofetil 250mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Mycophenolate Mofetil 500mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tacrolimus 0.5mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tacrolimus 1mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cyclosporin 25mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Cyclosporin 100mg Capsule", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Hydroxychloroquine 200mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Vaccines (Routine & Emergency) ───────────────────────────────────────
  { name: "BCG Vaccine", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Oral Polio Vaccine (OPV)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Inactivated Polio Vaccine (IPV)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "DTP-HepB-Hib Pentavalent Vaccine", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Hepatitis B Vaccine 10mcg", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Hepatitis B Vaccine 20mcg (Adult)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Hepatitis A Vaccine (Paediatric)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Hepatitis A Vaccine (Adult)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Yellow Fever Vaccine", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Meningococcal Vaccine (MenACWY)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Typhoid Vaccine (Vi Polysaccharide)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Pneumococcal Conjugate Vaccine (PCV13)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Rotavirus Vaccine (Oral)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "HPV Vaccine 0.5ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Influenza Vaccine (Quadrivalent)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Rabies Vaccine 2.5 IU/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Rabies Immunoglobulin 150 IU/ml Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tetanus Toxoid (TT) Vaccine", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Tetanus Immunoglobulin 250 IU Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "COVID-19 Vaccine (as stocked)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Anti-Snake Venom (Polyvalent) Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },

  // ── Miscellaneous / Antidotes & Emergency ────────────────────────────────
  { name: "Acetylcysteine 200mg/ml Injection (Paracetamol Antidote)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Atropine 1mg Injection (Organophosphate Antidote)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Pralidoxime (2-PAM) 500mg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Flumazenil 0.1mg/ml Injection (Benzodiazepine Antidote)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Naloxone 0.4mg/ml Injection (Opioid Antidote)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Digoxin-Specific Antibody (DigiFab) Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Desferrioxamine 500mg Injection (Iron Chelation)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Hydroxocobalamin 5g Injection (Cyanide Antidote)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Pyridoxine 100mg/ml Injection (Isoniazid Antidote)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Octreotide 50mcg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Octreotide 100mcg Injection", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Lactulose 30ml Sachet (Hepatic Encephalopathy)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Rifaximin 550mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ursodeoxycholic Acid 150mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Ursodeoxycholic Acid 300mg Tablet", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
  { name: "Zinc Acetate 25mg Capsule (Wilson's Disease)", category: "drug", price: "0", isVariablePrice: true, isSystem: false },
];